name: base_c10_resnet44_2
mode: train
ckpt: null
dataset: cifar10
data_dir: ./data
num_gpus: 1
model: hard_resnet44
loss: bce
clip: null
order: bn-relu
activation: relu
affine: true
epochs: 100
batch_size: 128
lr: !!float 1e-3
wd: !!float 1e-3
optimizer: adamw
seed: 0
error_model: random
inject_p: !!float 0.0
inject_epoch: 0
comment: Uniform noise [0, epoch). Inj each conv and linear layer. random model. p_c [0.75, 0.3, 0.1]. No single value injections.