name: c10_res44_test_02_bn-relu6_sgd
mode: train
ckpt: null
dataset: cifar10
data_dir: ./data
num_gpus: 1
model: hard_resnet44
loss: bce
clip: !!float 1.0
order: bn-relu
activation: relu6
affine: true
epochs: 100
batch_size: 128
lr: !!float 2.0
wd: !!float 1e-5
optimizer: sgd
seed: 0
error_model: square
inject_p: !!float 0.75
inject_epoch: 0
comment: Uniform noise [0, epoch). Inj each conv and linear layer. square model. p_c [0.3]. No single value injections.