name: ghostnetv2_clouds_p1
mode: validation
ckpt: "ckpt/bb_heads_clouds.pth"
dataset: sentinel
num_classes: 3
data_dir: ./data
num_gpus: 0
model: ghostnetv2
loss: ce
activation: relu6
batch_size: 32

# Injection parameters
seed: 0
error_model: random 
inject_p: !!float 1.0 #####################################
inject_epoch: 0
inject_index: -1 # -1 means all layers
nan: true
comment: Uniform noise [0, epoch). Inj each conv and linear layer. all model. p_c [0.1].

# Training parameters
clip: !!float 0.05
order: relu-bn
affine: false
epochs: 1
lr: !!float 1e-3
wd: !!float 1e-3
optimizer: adamw

# Criticality analysis
randrange: 1000
csv: ghostnetv2.csv
injsite: neuron

# Log
wandb: null
# log_stats: true # save layer output stats (pooling, activation, distribution)