# General
mode: validation
task: clouds # clouds or features
comment: null

# Environment
seed: 0
gpu: 0
wandb: null


# Data
dataset: sentinel
data_dir: ./data
split: test # test or validation
num_classes: 3 # 3 for clouds, 0 for features
batch_size: 64
num_workers: 8
pin_memory: true
drop_last: false
shuffle: false

# Model
model: ghostnetv2
ckpt: "ckpt/weights/bb_heads_clouds.pth"
width: 1.6
se_ratio: 0.25
loss: ce


# Fault Injection
inject: true ##############################################
inject_p: !!float 1e-3 ##################################
inject_index: -1 ########## -1 means all layers ###########
inject_first: true ########################################
inject_epoch: 0
error_model: random

# Fault Rejection
activation: relu6 #########################################
stats: false ##############################################
multiplier: 10.0 ##########################################
clip: false ###############################################
nan: true

# Fault Detection
detect: range #############################################
filter: false ############################################
detect_p: 0.13 ############################################
detect_index: -1 # last layer
mean: -0.55
std: 1.8
range: 15.0 ##############################################