# General
mode: validation
dataset: sentinel
data_dir: ./data
num_classes: 3
task: clouds # clouds or features
model: ghostnetv2

# Logging
ckpt: "ckpt/bb_heads_clouds.pth"
wandb: null

# Model
width: 1.6
se_ratio: 0.25
activation: relu6 #########################################
loss: ce

# Environment
num_gpus: 0
batch_size: 64
num_workers: 8
pin_memory: true
drop_last: false

# Injection
seed: 0
error_model: random
inject: true ##############################################
inject_p: !!float 1.0 #####################################
inject_index: 0 ########## -1 means all layers ###########
inject_first: true ########################################
inject_epoch: 0
nan: true
stats: null
comment: null

# Training (old)
clip: !!float 0.05
order: relu-bn
affine: false
epochs: 1
lr: !!float 1e-3
wd: !!float 1e-3
optimizer: adamw
optim_params: null

# run_pytorchfi.py (old)
randrange: 1000
csv: ghostnetv2.csv
injsite: neuron