name: c10_resnet44_base_full_injection_crit
mode: validate
ckpt: c10_resnet44_base_full_injection-epoch=152-val_acc=0.91.ckpt
dataset: cifar10
data_dir: ./data
num_gpus: 1
model: hard_resnet44
loss: bce
clip: null
order: bn-relu
activation: relu
affine: true
epochs: 160
batch_size: 128
lr: !!float 1e-3
wd: !!float 1e-3
optimizer: adamw
seed: 0
inject_p: !!float 0.00
inject_epoch: 0
comment: Testing the float differences.