name: ghostnetv2
mode: validation
ckpt: null
dataset: tinyimagenet
data_dir: ./data
num_gpus: 0
model: ghostnetv2
loss: bce
clip: !!float 0.05
order: relu-bn
activation: relu
affine: false
epochs: 1
batch_size: 128
lr: !!float 1e-3
wd: !!float 1e-3
optimizer: adamw
seed: 0
error_model: all
inject_p: !!float 0.03
inject_epoch: 0
comment: Uniform noise [0, epoch). Inj each conv and linear layer. all model. p_c [0.1].