name: line_c10_resnet44_2
mode: train
ckpt: null
dataset: cifar10
data_dir: ./data
num_gpus: 1
model: hard_resnet44
loss: bce
clip: !!float 0.05
order: relu-bn
activation: relu6
affine: false
epochs: 160
batch_size: 128
lr: !!float 1e-3
wd: !!float 1e-3
optimizer: adamw
seed: 0
error_model: line
inject_p: !!float 0.03
inject_epoch: 0
comment: Uniform noise [0, epoch). Inj each conv and linear layer. line model. p_c [0.75]. No single value injections.