name: c100_resnet44_randaug_wd
mode: train
ckpt: null
dataset: cifar100
data_dir: ./data
device: 0
model: hard_resnet44
loss: bce
clip: !!float 1.0
order: relu-bn
activation: relu6
affine: true
epochs: 200
batch_size: 128
lr: !!float 1e-3
wd: !!float 1e-3
optimizer: adamw
error_model: square
inject_p: !!float 0.75
inject_epoch: 0
label_smooth: !!float 0.0
jitter: !!float 0.0
rand_aug: rand-m7-mstd0.5-inc1
mixup_cutmix: False
rand_erasing: !!float 0.0
seed: 0
comment: test for augmentations