name: c100_resnet20_full_injection
mode: train
ckpt: null
dataset: cifar100
data_dir: ./data
num_gpus: 1
model: hard_resnet20
loss: bce
clip: !!float 0.05
order: relu-bn
activation: relu6
affine: false
epochs: 160
batch_size: 128
lr: !!float 1e-3
wd: !!float 1e-3
optimizer: adamw
seed: 0
inject_p: !!float 0.01
inject_epoch: 0
comment: Uniform noise [0, epoch). Injection at each convolution.