name: c100_resnet44_clipped_act
mode: train
ckpt: null
dataset: cifar100
data_dir: ./data
device: 0
model: hard_resnet44
loss: bce
clip: !!float 1.0
order: relu-bn
activation: relu6
affine: true
epochs: 100
batch_size: 128
lr: !!float 2
wd: !!float 1e-5
optimizer: sgd
error_model: square
inject_p: !!float 0.75
inject_epoch: 0
label_smooth: !!float 0.0
jitter: !!float 0.0
rand_aug: null
mixup_cutmix: False
rand_erasing: !!float 0.00
seed: 0
comment: gelu6, values > 10 are zeroized.