name: c100_resnet44_injection_after_conv
mode: train
ckpt: null
dataset: cifar100
data_dir: ./data
num_gpus: 1
model: resnet44
loss: bce
clip: !!float 0.05
order: relu-bn
activation: relu6
affine: false
epochs: 160
batch_size: 128
lr: !!float 1e-3
wd: !!float 1e-3
optimizer: adamw
seed: 0
inject_p: !!float 0.01
inject_epoch: 0
comment: Injection performed after the first convolution of the first ResBlock of the 2nd BlockGroup.