name: c10_resnet44_base_adamw_2
mode: train
ckpt: null
dataset: cifar10
data_dir: ./data
num_gpus: 1
model: resnet44
loss: bce
clip: null
order: bn-relu
activation: relu
affine: true
epochs: 160
batch_size: 128
lr: !!float 1e-3
wd: !!float 1e-2
optimizer: adamw
seed: 0
inject_p: !!float 0.0
inject_epoch: 161
comment: Injection at test time performed after the first convolution of the first ResBlock of the 2nd BlockGroup.