name: c10_res44_test_03_base
mode: train
ckpt: null
dataset: cifar10
data_dir: ./data
num_gpus: 1
model: hard_resnet44
loss: bce
clip: !!float 0.05
order: bn-relu
activation: relu
affine: true
epochs: 100
batch_size: 128
lr: !!float 1e-3
wd: !!float 1e-3
optimizer: adamw
seed: 0
error_model: square
inject_p: !!float 0.0
inject_epoch: 0
comment: Uniform noise [0, epoch). Inj each conv and linear layer. square model. p_c [0.3]. No single value injections.