name: default
mode: validation
ckpt: null
dataset: sentinel
data_dir: ./data
num_gpus: 0
model: resnet20
loss: bce
clip: null
norm: batch
epochs: 1
batch_size: 128
lr: !!float 1e-1
wd: !!float 1e-4
optimizer: sgd
seed: 0
inject_p: !!float 0.1
inject_epoch: 0
comment: null
wandb: null
nan: true