name: c10_res44_hard_gelu6_nans
mode: train
ckpt: null
dataset: cifar10
data_dir: ./data
device: 0
model: hard_resnet44
loss: bce
clip: !!float 1.0
order: relu-bn
activation: relu6
nan: true
affine: true
epochs: 100
batch_size: 128
lr: !!float 2.0
wd: !!float 1e-5
optimizer: sgd
seed: 0
error_model: square
inject_p: !!float 0.75
inject_epoch: 0
comment: gelu6 with nans
