name: test_blablablabla
mode: train
ckpt: null
dataset: cifar10
data_dir: ./data
num_gpus: 1
model: resnet44
loss: bce
clip: !!float 0.05
order: relu-bn
activation: relu6
affine: false
epochs: 160
batch_size: 128
lr: !!float 1e-3
wd: !!float 1e-3
optimizer: adamw
seed: 0
inject_p: !!float 0.02
inject_epoch: 0
comment: Uniform noise [0, epoch). Inj each conv and linear layer. SINGLE, LINE, SQUARE, ALL errors.